package enums;

public enum Attribute {
    KEYBOARD_SIZE,
    KEYBOARD_WIDTH,
    KEYBOARD_HEIGHT,
    GAP_SIZE,
    KEY_WIDTH,
    KEY_HEIGHT,
    SPACE_KEY_WIDTH,
    BACK_SPACE_KEY_WIDTH,
    SHIFT_KEY_WIDTH,
    ENTER_KEY_WIDTH,
    ROW_OFFSETS,
    KEY_ROWS,
    NUMBER_OF_KEYS,
    KEY_BINDINGS,
    DIST_TO_CAMERA,
    LEAP_PLANE_POINT_A,
    LEAP_PLANE_POINT_B,
    LEAP_PLANE_POINT_C;
}
