package enums;

public enum Attribute {
    KEYBOARD_SIZE,
    BORDER_SIZE,
    GAP_SIZE,
    KEY_SIZE,
    SPACE_KEY_SIZE,
    BACK_SPACE_KEY_SIZE,
    SHIFT_KEY_SIZE,
    ENTER_KEY_SIZE,
    ROW_OFFSETS,
    KEY_ROWS,
    NUMBER_OF_KEYS,
    CAMERA_DISTANCE,
    LEAP_PLANE_POINT_A,
    LEAP_PLANE_POINT_B,
    LEAP_PLANE_POINT_C,
    LEAP_PLANE_POINT_D;
}
