package enums;

public enum DataType {
    TIME_EXPERIMENT_START,
    TIME_EXPERIMENT_END,
    TIME_WORD_START,
    TIME_WORD_END,
    TIME_PRESSED,
    WORD_VALUE,
    KEY_PRESSED,
    KEY_PRESSED_UPPER,
    KEY_EXPECTED,
    KEY_EXPECTED_UPPER;
}
