package enums;

public enum ExitSurveyDataType {
    SUBJECT_ID,
    AGE,
    GENDER,
    MAJOR,
    HAS_PERSONAL_COMPUTER,
    HOURS_PER_WEEK_ON_COMPUTER,
    HAS_PREVIOUS_GESTURE_DEVICE_EXPERIENCE,
    PREVIOUS_GESTURE_DEVICE_DESCRIPTION,
    HAS_PREVIOUS_TOUCH_DEVICE_EXPERIENCE,
    PREVIOUS_TOUCH_DEVICE_DESCRIPTION,
    HAS_PREVIOUS_SWIPE_DEVICE_EXPERIENCE,
    PREVIOUS_SWIPE_DEVICE_DESCRIPTION,
    HAS_PHYSICAL_IMPAIRMENT,
    PHYSICAL_INPAIRMENT_DESCRIPTION,
    HANDEDNESS,
    PREFERED_HANDEDNESS_FOR_TOUCH_SCREENS,
    STANDARD_KEYBOARD_DISCOMFORT_LEVEL,
    TABLET_KEYBOARD_DISCOMFORT_LEVEL,
    CONTROLLER_KEYBOARD_DISCOMFORT_LEVEL,
    LEAP_SURFACE_KEYBOARD_DISCOMFORT_LEVEL,
    LEAP_AIR_KEYBOARD_DISCOMFORT_LEVEL,
    LEAP_PINCH_KEYBOARD_DISCOMFORT_LEVEL,
    STANDARD_KEYBOARD_FATIGUE_LEVEL,
    TABLET_KEYBOARD_FATIGUE_LEVEL,
    CONTROLLER_KEYBOARD_FATIGUE_LEVEL,
    LEAP_SURFACE_KEYBOARD_FATIGUE_LEVEL,
    LEAP_AIR_KEYBOARD_FATIGUE_LEVEL,
    LEAP_PINCH_KEYBOARD_FATIGUE_LEVEL,
    STANDARD_KEYBOARD_DIFFICULTY_LEVEL,
    TABLET_KEYBOARD_DIFFICULTY_LEVEL,
    CONTROLLER_KEYBOARD_DIFFICULTY_LEVEL,
    LEAP_SURFACE_KEYBOARD_DIFFICULTY_LEVEL,
    LEAP_AIR_KEYBOARD_DIFFICULTY_LEVEL,
    LEAP_PINCH_KEYBOARD_DIFFICULTY_LEVEL,
    STANDARD_KEYBOARD_PREFERENCE_RATING,
    TABLET_KEYBOARD_PREFERENCE_RATING,
    CONTROLLER_KEYBOARD_PREFERENCE_RATING,
    LEAP_SURFACE_KEYBOARD_PREFERENCE_RATING,
    LEAP_AIR_KEYBOARD_PREFERENCE_RATING,
    LEAP_PINCH_KEYBOARD_PREFERENCE_RATING;
    
    private static final ExitSurveyDataType[] VALUES = values();
    private static final int SIZE = VALUES.length;
    
    public static ExitSurveyDataType getByName(String typeName) {
        for(int i = 0; i < SIZE; i++) {
            if(VALUES[i].name().equalsIgnoreCase(typeName)) return VALUES[i];
        }
        return null;
    }
}
