package enums;

public enum StatisticDataType {
    TEXT_ENTRY_RATE_WPM(),
    ERROR_RATE_KSPC(),
    ERROR_RATE_MODIFIED_MSD(),
    FRECHET_DISTANCE(),
    EXPECTED_PATH_POINTS(),
    TRAVELED_PATH_POINTS_TOUCH_ONLY(),
    TOTAL_DISTANCE_EXPECTED_PER_WORD(),
    TOTAL_DISTANCE_TRAVELED_PER_WORD(),
    TOTAL_DISTANCE_EXPECTED_TOTAL(),
    TOTAL_DISTANCE_TRAVELED_TOTAL(),
    REACTION_TIME_PER_WORD(),
    REACTION_TIME_AVERAGE_PER_INPUT(),
    REACTION_TIME_TO_ERRORS_PER_WORD(),
    REACTION_TIME_TO_ERRORS_AVERAGE_PER_INPUT(),
    TIME_DURATION_PER_WORD(),
    CORRECTED_TIME_DURATION_PER_WORD(), // same function as modified MSD -- we detect word as finished upon seeing match ignoring errors
    TOTAL_TIME_DURATION_PER_INPUT(), // can just get total time 
    CORRECTED_TOTAL_TIME_DURATION_PER_INPUT(),
    
}
